how to fix a misused meshkit logger
meshery/meshery-istio pull request #301
Opened 2021-11-10 12:35 UTC by DelusionalOptimist

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes an instance of misused meshkit logger

**Notes for Reviewers**
**We need to replace this everywhere to prevent frequent panics which are hiding in plain sight but are noticed only when an error actually occurs.**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-11-10 14:11 UTC, sayantan1413 reviewed
Yes, I agree @DelusionalOptimist it makes sense to me. I think we have skipped some of this and so we need to fix it.

2021-11-10 14:28 UTC, Mr-DG-Wick commented on istio/sample_apps.go
> +	// The below function returns Go's built in error type but we can't
```suggestion
	// The below function returns Go's built-in error type but we can't
```

2021-11-10 14:30 UTC, Mr-DG-Wick requested changes

2021-11-11 12:04 UTC, DelusionalOptimist commented on istio/sample_apps.go
> +	// The below function returns Go's built in error type but we can't
:heavy_check_mark:

2021-11-12 12:17 UTC, leecalcote commented
@Shreyas220 will you add a note on this to https://docs.meshery.io/project/contributing/contributing-error?

2021-11-12 12:18 UTC, leecalcote commented
@Shreyas220 will you examine other adapters for this same need to change the error logging?

2021-11-12 13:31 UTC, Shreyas220 commented
> @Shreyas220 will you add a note on this to https://docs.meshery.io/project/contributing/contributing-error?

@DelusionalOptimist has added the docs already in https://github.com/meshery/meshery/pull/4594

2021-12-03 19:56 UTC, Revolyssup approved these changes

2021-12-03 19:56 UTC, merged