Logo updated to meshery from layer5
meshery/meshery-istio pull request #576
Opened 2023-05-08 17:51 UTC by duckling69

**Description**

This PR fixes issue  #568 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-05-15 11:24 UTC, goldfishdolphin commented on .github/config.yml
> +  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Meshery-darkmode-celebration.svg">
@duckling69  Please have a look at the path <source media="(prefers-color-scheme: dark)"
srcset="https://raw.githubusercontent.com/meshery/meshery-istio/master/.github/welcome/Meshery-darkmode-celebration.svg">

2023-05-15 13:31 UTC, thisiskaransgit requested changes

2023-05-15 16:33 UTC, duckling69 commented
@goldfishdolphin @thisiskaransgit done with all reviewed changes

2023-05-16 09:56 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-05-16 11:07 UTC, goldfishdolphin approved these changes
Good Job @duckling69! 
Thank you  for your contribution.

2023-06-09 11:08 UTC, theBeginner86 approved these changes

2023-06-09 11:08 UTC, merged